version: "3.9"

services:
  db:
    image: postgres:16
    container_name: food_delivery_db
    restart: always
    environment:
      POSTGRES_DB: food_delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: food_delivery_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

volumes:
  postgres_data: